In [685]:
import numpy as np
from IPython.display import HTML, display
import tabulate

In [686]:
#State abbreviations: https://en.wikipedia.org/wiki/List_of_states_and_territories_of_the_United_States#States
#Cases: https://covid.cdc.gov/covid-data-tracker/#cases_totalcases
#Vaccinations: https://usafacts.org/visualizations/covid-vaccine-tracker-states/

In [687]:
#Data

In [688]:
caseDate = "11-28-2021"

In [689]:
vaccDate = "11-24-2021"

In [690]:
#Alabama Cases

#State
ALstate = "AL"

#Cases in the last 7 days
AL7case = "02272"

#Cases in the last 7 days per 100k people
AL7case100 = "046.3"

#Total Cases
ALcase = "0844953"

#Total Cases per 100k people
ALcase100 = "17233"

#Alabama Vaccinations

#% with 1 dose
ALvacc1per = "56.21"

#1 dose
ALvacc1 = "02755913"

#% with 2 doses
ALvacc2per = "45.98"

#2 doses
ALvacc2 = "02254666"

#Array of AL data
AL = np.array([ALstate,
               AL7case,
               AL7case100,
               ALcase,
               ALcase100,
               ALvacc1per,
               ALvacc1,
               ALvacc2per,
               ALvacc2])

In [691]:
#Alaska Cases

#State
AKstate = "AK"

#Cases in the last 7 days
AK7case = "01975"

#Cases in the last 7 days per 100k people
AK7case100 = "270.0"

#Total Cases
AKcase = "0144692"

#Total Cases per 100k people
AKcase100 = "19779"

#Alaska Vaccinations

#% with 1 dose
AKvacc1per = "62.28"

#1 dose
AKvacc1 = "00455580"

#% with 2 doses
AKvacc2per = "54.02"

#2 doses
AKvacc2 = "00395164"

#Array of AK data
AK = np.array([AKstate,
               AK7case,
               AK7case100,
               AKcase,
               AKcase100,
               AKvacc1per,
               AKvacc1,
               AKvacc2per,
               AKvacc2])

In [692]:
#Arizona Cases

#State
AZstate = "AZ"

#Cases in the last 7 days
AZ7case = "25773"

#Cases in the last 7 days per 100k people
AZ7case100 = "354.1"

#Total Cases
AZcase = "1258919"

#Total Cases per 100k people
AZcase100 = "17296"

#Arizona Vaccinations

#% with 1 dose
AZvacc1per = "63.77"

#1 dose
AZvacc1 = "04641772"

#% with 2 doses
AZvacc2per = "54.43"

#2 doses
AZvacc2 = "03961885"

#Array of AZ data
AZ = np.array([AZstate,
               AZ7case,
               AZ7case100,
               AZcase,
               AZcase100,
               AZvacc1per,
               AZvacc1,
               AZvacc2per,
               AZvacc2])

In [693]:
#Arkansas Cases

#State
ARstate = "AR"

#Cases in the last 7 days
AR7case = "03514"

#Cases in the last 7 days per 100k people
AR7case100 = "116.4"

#Total Cases
ARcase = "0526706"

#Total Cases per 100k people
ARcase100 = "17453"

#Arkansas Vaccinations

#% with 1 dose
ARvacc1per = "59.97"

#1 dose
ARvacc1 = "01809847"

#% with 2 doses
ARvacc2per = "49.05"

#2 doses
ARvacc2 = "01480277"

#Array of AR data
AR = np.array([ARstate,
               AR7case,
               AR7case100,
               ARcase,
               ARcase100,
               ARvacc1per,
               ARvacc1,
               ARvacc2per,
               ARvacc2])

In [694]:
#California Cases

#State
CAstate = "CA"

#Cases in the last 7 days
CA7case = "22570"

#Cases in the last 7 days per 100k people
CA7case100 = "057.1"

#Total Cases
CAcase = "5036998"

#Total Cases per 100k people
CAcase100 = "12748"

#California Vaccinations

#% with 1 dose
CAvacc1per = "78.17"

#1 dose
CAvacc1 = "30866780"

#% with 2 doses
CAvacc2per = "62.84"

#2 doses
CAvacc2 = "24827738"

#Array of CA data
CA = np.array([CAstate,
               CA7case,
               CA7case100,
               CAcase,
               CAcase100,
               CAvacc1per,
               CAvacc1,
               CAvacc2per,
               CAvacc2])

In [695]:
#Colorado Cases

#State
COstate = "CO"

#Cases in the last 7 days
CO7case = "17125"

#Cases in the last 7 days per 100k people
CO7case100 = "297.4"

#Total Cases
COcase = "0821859"

#Total Cases per 100k people
COcase100 = "14272"

#Colorado Vaccinations

#% with 1 dose
COvacc1per = "70.94"

#1 dose
COvacc1 = "04085143"

#% with 2 doses
COvacc2per = "62.93"

#2 doses
COvacc2 = "03623786"

#Array of CO data
CO = np.array([COstate,
               CO7case,
               CO7case100,
               COcase,
               COcase100,
               COvacc1per,
               COvacc1,
               COvacc2per,
               COvacc2])

In [696]:
#Connecticut Cases

#State
CTstate = "CT"

#Cases in the last 7 days
CT7case = "05555"

#Cases in the last 7 days per 100k people
CT7case100 = "155.8"

#Total Cases
CTcase = "0418473"

#Total Cases per 100k people
CTcase100 = "11737"

#Connecticut Vaccinations

#% with 1 dose
CTvacc1per = "83.32"

#1 dose
CTvacc1 = "02970430"

#% with 2 doses
CTvacc2per = "71.75"

#2 doses
CTvacc2 = "02558052"

#Array of CT data
CT = np.array([CTstate,
               CT7case,
               CT7case100,
               CTcase,
               CTcase100,
               CTvacc1per,
               CTvacc1,
               CTvacc2per,
               CTvacc2])

In [697]:
#Delaware Cases

#State
DEstate = "DE"

#Cases in the last 7 days
DE7case = "02599"

#Cases in the last 7 days per 100k people
DE7case100 = "266.9"

#Total Cases
DEcase = "0152165"

#Total Cases per 100k people
DEcase100 = "15626"

#Delaware Vaccinations

#% with 1 dose
DEvacc1per = "71.37"

#1 dose
DEvacc1 = "00694961"

#% with 2 doses
DEvacc2per = "60.93"

#2 doses
DEvacc2 = "00593295"

#Array of DE data
DE = np.array([DEstate,
               DE7case,
               DE7case100,
               DEcase,
               DEcase100,
               DEvacc1per,
               DEvacc1,
               DEvacc2per,
               DEvacc2])

In [698]:
#District of Columbia Cases
#State
DCstate = "DC"

#Cases in the last 7 days
DC7case = "00482"

#Cases in the last 7 days per 100k people
DC7case100 = "068.3"

#Total Cases
DCcase = "0066510"

#Total Cases per 100k people
DCcase100 = "09424"

#District of Columbia Vaccinations

#% with 1 dose
DCvacc1per = "80.60"

#1 dose
DCvacc1 = "00568837"

#% with 2 doses
DCvacc2per = "64.09"

#2 doses
DCvacc2 = "00452301"

#Array of DC data
DC = np.array([DCstate,
               DC7case,
               DC7case100,
               DCcase,
               DCcase100,
               DCvacc1per,
               DCvacc1,
               DCvacc2per,
               DCvacc2])

In [699]:
#Florida Cases

#State
FLstate = "FL"

#Cases in the last 7 days
FL7case = "05890"

#Cases in the last 7 days per 100k people
FL7case100 = "027.4"

#Total Cases
FLcase = "3684999"

#Total Cases per 100k people
FLcase100 = "17157"

#Florida Vaccinations

#% with 1 dose
FLvacc1per = "71.32"

#1 dose
FLvacc1 = "15318838"

#% with 2 doses
FLvacc2per = "61.00"

#2 doses
FLvacc2 = "13100793"

#Array of FL data
FL = np.array([FLstate,
               FL7case,
               FL7case100,
               FLcase,
               FLcase100,
               FLvacc1per,
               FLvacc1,
               FLvacc2per,
               FLvacc2])

In [700]:
#Georgia Cases

#State
GAstate = "GA"

#Cases in the last 7 days
GA7case = "04842"

#Cases in the last 7 days per 100k people
GA7case100 = "045.6"

#Total Cases
GAcase = "1659491"

#Total Cases per 100k people
GAcase100 = "15630"

#Georgia Vaccinations

#% with 1 dose
GAvacc1per = "58.61"

#1 dose
GAvacc1 = "06223181"

#% with 2 doses
GAvacc2per = "49.37"

#2 doses
GAvacc2 = "05241785"

#Array of GA data
GA = np.array([GAstate,
               GA7case,
               GA7case100,
               GAcase,
               GAcase100,
               GAvacc1per,
               GAvacc1,
               GAvacc2per,
               GAvacc2])

In [701]:
#Hawaii Cases

#State
HIstate = "HI"

#Cases in the last 7 days
HI7case = "00650"

#Cases in the last 7 days per 100k people
HI7case100 = "045.9"

#Total Cases
HIcase = "0084334"

#Total Cases per 100k people
HIcase100 = "05956"

#Hawaii Vaccinations

#% with 1 dose
HIvacc1per = "81.67"

#1 dose
HIvacc1 = "01156297"

#% with 2 doses
HIvacc2per = "60.74"

#2 doses
HIvacc2 = "00859993"

#Array of HI data
HI = np.array([HIstate,
               HI7case,
               HI7case100,
               HIcase,
               HIcase100,
               HIvacc1per,
               HIvacc1,
               HIvacc2per,
               HIvacc2])

In [702]:
#Idaho Cases

#State
IDstate = "ID"

#Cases in the last 7 days
ID7case = "02474"

#Cases in the last 7 days per 100k people
ID7case100 = "138.4"

#Total Cases
IDcase = "0305524"

#Total Cases per 100k people
IDcase100 = "17096"

#Idaho Vaccinations

#% with 1 dose
IDvacc1per = "50.50"

#1 dose
IDvacc1 = "00902388"

#% with 2 doses
IDvacc2per = "45.05"

#2 doses
IDvacc2 = "00805110"

#Array of ID data
ID = np.array([IDstate,
               ID7case,
               ID7case100,
               IDcase,
               IDcase100,
               IDvacc1per,
               IDvacc1,
               IDvacc2per,
               IDvacc2])

In [703]:
#Illinois Cases

#State
ILstate = "IL"

#Cases in the last 7 days
IL7case = "21034"

#Cases in the last 7 days per 100k people
IL7case100 = "166.0"

#Total Cases
ILcase = "1784900"

#Total Cases per 100k people
ILcase100 = "14086"

#Illinois Vaccinations

#% with 1 dose
ILvacc1per = "68.69"

#1 dose
ILvacc1 = "08703666"

#% with 2 doses
ILvacc2per = "61.37"

#2 doses
ILvacc2 = "07776092"

#Array of IL data
IL = np.array([ILstate,
               IL7case,
               IL7case100,
               ILcase,
               ILcase100,
               ILvacc1per,
               ILvacc1,
               ILvacc2per,
               ILvacc2])

In [704]:
#Indiana Cases

#State
INstate = "IN"

#Cases in the last 7 days
IN7case = "15038"

#Cases in the last 7 days per 100k people
IN7case100 = "223.4"

#Total Cases
INcase = "1084488"

#Total Cases per 100k people
INcase100 = "16109"

#Indiana Vaccinations

#% with 1 dose
INvacc1per = "55.52"

#1 dose
INvacc1 = "03737561"

#% with 2 doses
INvacc2per = "50.53"

#2 doses
INvacc2 = "03401497"

#Array of IN data
IN = np.array([INstate,
               IN7case,
               IN7case100,
               INcase,
               INcase100,
               INvacc1per,
               INvacc1,
               INvacc2per,
               INvacc2])

In [705]:
#Iowa Cases

#State
IAstate = "IA"

#Cases in the last 7 days
IA7case = "09221"

#Cases in the last 7 days per 100k people
IA7case100 = "292.3"

#Total Cases
IAcase = "0522858"

#Total Cases per 100k people
IAcase100 = "16572"

#Iowa Vaccinations

#% with 1 dose
IAvacc1per = "62.21"

#1 dose
IAvacc1 = "01962641"

#% with 2 doses
IAvacc2per = "56.50"

#2 doses
IAvacc2 = "01782766"

#Array of IA data
IA = np.array([IAstate,
               IA7case,
               IA7case100,
               IAcase,
               IAcase100,
               IAvacc1per,
               IAvacc1,
               IAvacc2per,
               IAvacc2])

In [706]:
#Kansas Cases

#State
KSstate = "KS"

#Cases in the last 7 days
KS7case = "05374"

#Cases in the last 7 days per 100k people
KS7case100 = "184.5"

#Total Cases
KScase = "0461163"

#Total Cases per 100k people
KScase100 = "15830"

#Kansas Vaccinations

#% with 1 dose
KSvacc1per = "65.66"

#1 dose
KSvacc1 = "01912921"

#% with 2 doses
KSvacc2per = "54.40"

#2 doses
KSvacc2 = "01584917"

#Array of KS data
KS = np.array([KSstate,
               KS7case,
               KS7case100,
               KScase,
               KScase100,
               KSvacc1per,
               KSvacc1,
               KSvacc2per,
               KSvacc2])

In [707]:
#Kentucky Cases

#State
KYstate = "KY"

#Cases in the last 7 days
KY7case = "09963"

#Cases in the last 7 days per 100k people
KY7case100 = "223.0"

#Total Cases
KYcase = "0780681"

#Total Cases per 100k people
KYcase100 = "17474"

#Kentucky Vaccinations

#% with 1 dose
KYvacc1per = "59.87"

#1 dose
KYvacc1 = "02674722"

#% with 2 doses
KYvacc2per = "51.90"

#2 doses
KYvacc2 = "02318846"

#Array of KY data
KY = np.array([KYstate,
               KY7case,
               KY7case100,
               KYcase,
               KYcase100,
               KYvacc1per,
               KYvacc1,
               KYvacc2per,
               KYvacc2])

In [708]:
#Louisiana Cases

#State
LAstate = "LA"

#Cases in the last 7 days
LA7case = "01721"

#Cases in the last 7 days per 100k people
LA7case100 = "037.0"

#Total Cases
LAcase = "0769051"

#Total Cases per 100k people
LAcase100 = "16543"

#Louisiana Vaccinations

#% with 1 dose
LAvacc1per = "55.26"

#1 dose
LAvacc1 = "02568779"

#% with 2 doses
LAvacc2per = "48.66"

#2 doses
LAvacc2 = "02262153"

#Array of LA data
LA = np.array([LAstate,
               LA7case,
               LA7case100,
               LAcase,
               LAcase100,
               LAvacc1per,
               LAvacc1,
               LAvacc2per,
               LAvacc2])

In [709]:
#Maine Cases

#State
MEstate = "ME"

#Cases in the last 7 days
ME7case = "02643"

#Cases in the last 7 days per 100k people
ME7case100 = "196.6"

#Total Cases
MEcase = "0118489"

#Total Cases per 100k people
MEcase100 = "08815"

#Maine Vaccinations

#% with 1 dose
MEvacc1per = "81.37"

#1 dose
MEvacc1 = "01093735"

#% with 2 doses
MEvacc2per = "72.05"

#2 doses
MEvacc2 = "00968553"

#Array of ME data
ME = np.array([MEstate,
               ME7case,
               ME7case100,
               MEcase,
               MEcase100,
               MEvacc1per,
               MEvacc1,
               MEvacc2per,
               MEvacc2])

In [710]:
#Maryland Cases

#State
MDstate = "MD"

#Cases in the last 7 days
MD7case = "06286"

#Cases in the last 7 days per 100k people
MD7case100 = "104.0"

#Total Cases
MDcase = "0583299"

#Total Cases per 100k people
MDcase100 = "09648"

#Maryland Vaccinations

#% with 1 dose
MDvacc1per = "76.42"

#1 dose
MDvacc1 = "04619856"

#% with 2 doses
MDvacc2per = "67.18"

#2 doses
MDvacc2 = "04061450"

#Array of MD data
MD = np.array([MDstate,
               MD7case,
               MD7case100,
               MDcase,
               MDcase100,
               MDvacc1per,
               MDvacc1,
               MDvacc2per,
               MDvacc2])

In [711]:
#Massachusetts Cases

#State
MAstate = "MA"

#Cases in the last 7 days
MA7case = "18972"

#Cases in the last 7 days per 100k people
MA7case100 = "275.3"

#Total Cases
MAcase = "0909705"

#Total Cases per 100k people
MAcase100 = "13198"

#Massachusetts Vaccinations

#% with 1 dose
MAvacc1per = "84.98"

#1 dose
MAvacc1 = "05856929"

#% with 2 doses
MAvacc2per = "70.85"

#2 doses
MAvacc2 = "04883284"

#Array of MA data
MA = np.array([MAstate,
               MA7case,
               MA7case100,
               MAcase,
               MAcase100,
               MAvacc1per,
               MAvacc1,
               MAvacc2per,
               MAvacc2])

In [712]:
#Michigan Cases

#State
MIstate = "MI"

#Cases in the last 7 days
MI7case = "38811"

#Cases in the last 7 days per 100k people
MI7case100 = "388.6"

#Total Cases
MIcase = "1447230"

#Total Cases per 100k people
MIcase100 = "14491"

#Michigan Vaccinations

#% with 1 dose
MIvacc1per = "60.77"

#1 dose
MIvacc1 = "06069178"

#% with 2 doses
MIvacc2per = "54.41"

#2 doses
MIvacc2 = "05433838"

#Array of MI data
MI = np.array([MIstate,
               MI7case,
               MI7case100,
               MIcase,
               MIcase100,
               MIvacc1per,
               MIvacc1,
               MIvacc2per,
               MIvacc2])

In [713]:
#Minnesota Cases

#State
MNstate = "MN"

#Cases in the last 7 days
MN7case = "24026"

#Cases in the last 7 days per 100k people
MN7case100 = "426.0"

#Total Cases
MNcase = "0895229"

#Total Cases per 100k people
MNcase100 = "15874"

#Minnesota Vaccinations

#% with 1 dose
MNvacc1per = "68.53"

#1 dose
MNvacc1 = "03864994"

#% with 2 doses
MNvacc2per = "62.21"

#2 doses
MNvacc2 = "03508269"

#Array of MN data
MN = np.array([MNstate,
               MN7case,
               MN7case100,
               MNcase,
               MNcase100,
               MNvacc1per,
               MNvacc1,
               MNvacc2per,
               MNvacc2])

In [714]:
#Mississippi Cases

#State
MSstate = "MS"

#Cases in the last 7 days
MS7case = "01884"

#Cases in the last 7 days per 100k people
MS7case100 = "063.3"

#Total Cases
MScase = "0512632"

#Total Cases per 100k people
MScase100 = "17225"

#Mississippi Vaccinations

#% with 1 dose
MSvacc1per = "53.68"

#1 dose
MSvacc1 = "01597621"

#% with 2 doses
MSvacc2per = "46.89"

#2 doses
MSvacc2 = "01395494"

#Array of MS data
MS = np.array([MSstate,
               MS7case,
               MS7case100,
               MScase,
               MScase100,
               MSvacc1per,
               MSvacc1,
               MSvacc2per,
               MSvacc2])

In [715]:
#Missouri Cases

#State
MOstate = "MO"

#Cases in the last 7 days
MO7case = "05894"

#Cases in the last 7 days per 100k people
MO7case100 = "096.0"

#Total Cases
MOcase = "0898243"

#Total Cases per 100k people
MOcase100 = "14636"

#Missouri Vaccinations

#% with 1 dose
MOvacc1per = "59.36"

#1 dose
MOvacc1 = "03642900"

#% with 2 doses
MOvacc2per = "50.79"

#2 doses
MOvacc2 = "03117242"

#Array of MO data
MO = np.array([MOstate,
               MO7case,
               MO7case100,
               MOcase,
               MOcase100,
               MOvacc1per,
               MOvacc1,
               MOvacc2per,
               MOvacc2])

In [716]:
#Montana Cases

#State
MTstate = "MT"

#Cases in the last 7 days
MT7case = "02058"

#Cases in the last 7 days per 100k people
MT7case100 = "192.6"

#Total Cases
MTcase = "0190071"

#Total Cases per 100k people
MTcase100 = "17784"

#Montana Vaccinations

#% with 1 dose
MTvacc1per = "59.42"

#1 dose
MTvacc1 = "00635021"

#% with 2 doses
MTvacc2per = "51.72"

#2 doses
MTvacc2 = "00552782"

#Array of MT data
MT = np.array([MTstate,
               MT7case,
               MT7case100,
               MTcase,
               MTcase100,
               MTvacc1per,
               MTvacc1,
               MTvacc2per,
               MTvacc2])

In [717]:
#Nebraska Cases

#State
NEstate = "NE"

#Cases in the last 7 days
NE7case = "05329"

#Cases in the last 7 days per 100k people
NE7case100 = "275.5"

#Total Cases
NEcase = "0307896"

#Total Cases per 100k people
NEcase100 = "15917"

#Nebraska Vaccinations

#% with 1 dose
NEvacc1per = "63.70"

#1 dose
NEvacc1 = "01232270"

#% with 2 doses
NEvacc2per = "57.20"

#2 doses
NEvacc2 = "01106433"

#Array of NE data
NE = np.array([NEstate,
               NE7case,
               NE7case100,
               NEcase,
               NEcase100,
               NEvacc1per,
               NEvacc1,
               NEvacc2per,
               NEvacc2])

In [718]:
#Nevada Cases

#State
NVstate = "NV"

#Cases in the last 7 days
NV7case = "03141"

#Cases in the last 7 days per 100k people
NV7case100 = "102.0"

#Total Cases
NVcase = "0467774"

#Total Cases per 100k people
NVcase100 = "15187"

#Nevada Vaccinations

#% with 1 dose
NVvacc1per = "65.93"

#1 dose
NVvacc1 = "02030864"

#% with 2 doses
NVvacc2per = "54.24"

#2 doses
NVvacc2 = "01670646"

#Array of NV data
NV = np.array([NVstate,
               NV7case,
               NV7case100,
               NVcase,
               NVcase100,
               NVvacc1per,
               NVvacc1,
               NVvacc2per,
               NVvacc2])

In [719]:
#New Hampshire Cases

#State
NHstate = "NH"

#Cases in the last 7 days
NH7case = "04898"

#Cases in the last 7 days per 100k people
NH7case100 = "360.2"

#Total Cases
NHcase = "0155711"

#Total Cases per 100k people
NHcase100 = "11452"

#New Hampshire Vaccinations

#% with 1 dose
NHvacc1per = "86.27"

#1 dose
NHvacc1 = "01173089"

#% with 2 doses
NHvacc2per = "64.63"

#2 doses
NHvacc2 = "00878808"

#Array of NH data
NH = np.array([NHstate,
               NH7case,
               NH7case100,
               NHcase,
               NHcase100,
               NHvacc1per,
               NHvacc1,
               NHvacc2per,
               NHvacc2])

In [720]:
#New Jersey Cases

#State
NJstate = "NJ"

#Cases in the last 7 days
NJ7case = "15187"

#Cases in the last 7 days per 100k people
NJ7case100 = "171.0"

#Total Cases
NJcase = "1243354"

#Total Cases per 100k people
NJcase100 = "13998"

#New Jersey Vaccinations

#% with 1 dose
NJvacc1per = "78.44"

#1 dose
NJvacc1 = "06966872"

#% with 2 doses
NJvacc2per = "67.52"

#2 doses
NJvacc2 = "05997187"

#Array of NJ data
NJ = np.array([NJstate,
               NJ7case,
               NJ7case100,
               NJcase,
               NJcase100,
               NJvacc1per,
               NJvacc1,
               NJvacc2per,
               NJvacc2])

In [721]:
#New Mexico Cases

#State
NMstate = "NM"

#Cases in the last 7 days
NM7case = "06154"

#Cases in the last 7 days per 100k people
NM7case100 = "293.5"

#Total Cases
NMcase = "0308091"

#Total Cases per 100k people
NMcase100 = "14693"

#New Mexico Vaccinations

#% with 1 dose
NMvacc1per = "76.04"

#1 dose
NMvacc1 = "01594411"

#% with 2 doses
NMvacc2per = "63.33"

#2 doses
NMvacc2 = "01328003"

#Array of NM data
NM = np.array([NMstate,
               NM7case,
               NM7case100,
               NMcase,
               NMcase100,
               NMvacc1per,
               NMvacc1,
               NMvacc2per,
               NMvacc2])

In [722]:
#New York Cases

#State
NYstate = "NY"

#Cases in the last 7 days
NY7case = "47112"

#Cases in the last 7 days per 100k people
NY7case100 = "242.2"

#Total Cases
NYcase = "2706423"

#Total Cases per 100k people
NYcase100 = "13913"

#New York Vaccinations

#% with 1 dose
NYvacc1per = "77.49"

#1 dose
NYvacc1 = "15075041"

#% with 2 doses
NYvacc2per = "68.20"

#2 doses
NYvacc2 = "13268116"

#Array of NY data
NY = np.array([NYstate,
               NY7case,
               NY7case100,
               NYcase,
               NYcase100,
               NYvacc1per,
               NYvacc1,
               NYvacc2per,
               NYvacc2])

In [723]:
#North Carolina Cases

#State
NCstate = "NC"

#Cases in the last 7 days
NC7case = "09199"

#Cases in the last 7 days per 100k people
NC7case100 = "087.7"

#Total Cases
NCcase = "1524078"

#Total Cases per 100k people
NCcase100 = "14532"

#North Carolina Vaccinations

#% with 1 dose
NCvacc1per = "69.43"

#1 dose
NCvacc1 = "07282242"

#% with 2 doses
NCvacc2per = "53.97"

#2 doses
NCvacc2 = "05660326"

#Array of NC data
NC = np.array([NCstate,
               NC7case,
               NC7case100,
               NCcase,
               NCcase100,
               NCvacc1per,
               NCvacc1,
               NCvacc2per,
               NCvacc2])

In [724]:
#North Dakota Cases

#State
NDstate = "ND"

#Cases in the last 7 days
ND7case = "02755"

#Cases in the last 7 days per 100k people
ND7case100 = "361.5"

#Total Cases
NDcase = "0161093"

#Total Cases per 100k people
NDcase100 = "21139"

#North Dakota Vaccinations7

#% with 1 dose
NDvacc1per = "55.56"

#1 dose
NDvacc1 = "00438649"

#% with 2 doses
NDvacc2per = "48.60"

#2 doses
NDvacc2 = "00370361"

#Array of ND data
ND = np.array([NDstate,
               ND7case,
               ND7case100,
               NDcase,
               NDcase100,
               NDvacc1per,
               NDvacc1,
               NDvacc2per,
               NDvacc2])

In [725]:
#Ohio Cases

#State
OHstate = "OH"

#Cases in the last 7 days
OH7case = "35794"

#Cases in the last 7 days per 100k people
OH7case100 = "306.2"

#Total Cases
OHcase = "1669274"

#Total Cases per 100k people
OHcase100 = "14281"

#Ohio Vaccinations

#% with 1 dose
OHvacc1per = "58.00"

#1 dose
OHvacc1 = "06779515"

#% with 2 doses
OHvacc2per = "52.83"

#2 doses
OHvacc2 = "06175735"

#Array of OH data
OH = np.array([OHstate,
               OH7case,
               OH7case100,
               OHcase,
               OHcase100,
               OHvacc1per,
               OHvacc1,
               OHvacc2per,
               OHvacc2])

In [726]:
#Oklahoma Cases

#State
OKstate = "OK"

#Cases in the last 7 days
OK7case = "03580"

#Cases in the last 7 days per 100k people
OK7case100 = "090.5"

#Total Cases
OKcase = "0663165"

#Total Cases per 100k people
OKcase100 = "16759"

#Oklahoma Vaccinations

#% with 1 dose
OKvacc1per = "62.33"

#1 dose
OKvacc1 = "02466343"

#% with 2 doses
OKvacc2per = "51.31"

#2 doses
OKvacc2 = "02030324"

#Array of OK data
OK = np.array([OKstate,
               OK7case,
               OK7case100,
               OKcase,
               OKcase100,
               OKvacc1per,
               OKvacc1,
               OKvacc2per,
               OKvacc2])

In [727]:
#Oregon Cases

#State
ORstate = "OR"

#Cases in the last 7 days
OR7case = "03423"

#Cases in the last 7 days per 100k people
OR7case100 = "081.2"

#Total Cases
ORcase = "0387485"

#Total Cases per 100k people
ORcase100 = "09187"

#Oregon Vaccinations

#% with 1 dose
ORvacc1per = "71.05"

#1 dose
ORvacc1 = "02966512"

#% with 2 doses
ORvacc2per = "63.84"

#2 doses
ORvacc2 = "02692675"

#Array of OR data
OR = np.array([ORstate,
               OR7case,
               OR7case100,
               ORcase,
               ORcase100,
               ORvacc1per,
               ORvacc1,
               ORvacc2per,
               ORvacc2])

In [728]:
#Pennsylvania Cases

#State
PAstate = "PA"

#Cases in the last 7 days
PA7case = "42272"

#Cases in the last 7 days per 100k people
PA7case100 = "330.2"

#Total Cases
PAcase = "1716600"

#Total Cases per 100k people
PAcase100 = "13409"

#Pennsylvania Vaccinations

#% with 1 dose
PAvacc1per = "80.85"

#1 dose
PAvacc1 = "10349983"

#% with 2 doses
PAvacc2per = "58.05"

#2 doses
PAvacc2 = "07430988"

#Array of PA data
PA = np.array([PAstate,
               PA7case,
               PA7case100,
               PAcase,
               PAcase100,
               PAvacc1per,
               PAvacc1,
               PAvacc2per,
               PAvacc2])

In [729]:
#Rhode Island Cases

#State
RIstate = "RI"

#Cases in the last 7 days
RI7case = "02174"

#Cases in the last 7 days per 100k people
RI7case100 = "205.2"

#Total Cases
RIcase = "0188561"

#Total Cases per 100k people
RIcase100 = "17800"

#Rhode Island Vaccinations

#% with 1 dose
RIvacc1per = "82.41"

#1 dose
RIvacc1 = "00873059"

#% with 2 doses
RIvacc2per = "72.22"

#2 doses
RIvacc2 = "00765072"

#Array of RI data
RI = np.array([RIstate,
               RI7case,
               RI7case100,
               RIcase,
               RIcase100,
               RIvacc1per,
               RIvacc1,
               RIvacc2per,
               RIvacc2])

In [730]:
#South Carolina Cases

#State
SCstate = "SC"

#Cases in the last 7 days
SC7case = "03400"

#Cases in the last 7 days per 100k people
SC7case100 = "066.0"

#Total Cases
SCcase = "0914946"

#Total Cases per 100k people
SCcase100 = "17770"

#South Carolina Vaccinations

#% with 1 dose
SCvacc1per = "59.84"

#1 dose
SCvacc1 = "03080965"

#% with 2 doses
SCvacc2per = "51.17"

#2 doses
SCvacc2 = "02634512"

#Array of SC data
SC = np.array([SCstate,
               SC7case,
               SC7case100,
               SCcase,
               SCcase100,
               SCvacc1per,
               SCvacc1,
               SCvacc2per,
               SCvacc2])

In [731]:
#South Dakota Cases

#State
SDstate = "SD"

#Cases in the last 7 days
SD7case = "01917"

#Cases in the last 7 days per 100k people
SD7case100 = "216.7"

#Total Cases
SDcase = "0164292"

#Total Cases per 100k people
SDcase100 = "18571"

#South Dakota Vaccinations

#% with 1 dose
SDvacc1per = "66.33"

#1 dose
SDvacc1 = "00586804"

#% with 2 doses
SDvacc2per = "54.34"

#2 doses
SDvacc2 = "00480731"

#Array of SD data
SD = np.array([SDstate,
               SD7case,
               SD7case100,
               SDcase,
               SDcase100,
               SDvacc1per,
               SDvacc1,
               SDvacc2per,
               SDvacc2])

In [732]:
#Tennessee Cases

#State
TNstate = "TN"

#Cases in the last 7 days
TN7case = "06153"

#Cases in the last 7 days per 100k people
TN7case100 = "090.1"

#Total Cases
TNcase = "1309931"

#Total Cases per 100k people
TNcase100 = "19181"

#Tennessee Vaccinations

#% with 1 dose
TNvacc1per = "56.50"

#1 dose
TNvacc1 = "03858576"

#% with 2 doses
TNvacc2per = "49.39"

#2 doses
TNvacc2 = "03372783"

#Array of TN data
TN = np.array([TNstate,
               TN7case,
               TN7case100,
               TNcase,
               TNcase100,
               TNvacc1per,
               TNvacc1,
               TNvacc2per,
               TNvacc2])

In [733]:
#Texas Cases

#State
TXstate = "TX"

#Cases in the last 7 days
TX7case = "12852"

#Cases in the last 7 days per 100k people
TX7case100 = "044.3"

#Total Cases
TXcase = "4300466"

#Total Cases per 100k people
TXcase100 = "14831"

#Texas Vaccinations

#% with 1 dose
TXvacc1per = "63.71"

#1 dose
TXvacc1 = "18474428"

#% with 2 doses
TXvacc2per = "54.47"

#2 doses
TXvacc2 = "15793073"

#Array of TX data
TX = np.array([TXstate,
               TX7case,
               TX7case100,
               TXcase,
               TXcase100,
               TXvacc1per,
               TXvacc1,
               TXvacc2per,
               TXvacc2])

In [734]:
#Utah Cases

#State
UTstate = "UT"

#Cases in the last 7 days
UT7case = "09201"

#Cases in the last 7 days per 100k people
UT7case100 = "287.0"

#Total Cases
UTcase = "0592130"

#Total Cases per 100k people
UTcase100 = "18470"

#Utah Vaccinations

#% with 1 dose
UTvacc1per = "63.68"

#1 dose
UTvacc1 = "02041421"

#% with 2 doses
UTvacc2per = "55.24"

#2 doses
UTvacc2 = "01770907"

#Array of UT data
UT = np.array([UTstate,
               UT7case,
               UT7case100,
               UTcase,
               UTcase100,
               UTvacc1per,
               UTvacc1,
               UTvacc2per,
               UTvacc2])

In [735]:
#Vermont Cases

#State
VTstate = "VT"

#Cases in the last 7 days
VT7case = "01266"

#Cases in the last 7 days per 100k people
VT7case100 = "202.9"

#Total Cases
VTcase = "0044490"

#Total Cases per 100k people
VTcase100 = "07098"

#Vermont Vaccinations

#% with 1 dose
VTvacc1per = "84.59"

#1 dose
VTvacc1 = "00527825"

#% with 2 doses
VTvacc2per = "72.66"

#2 doses
VTvacc2 = "00453418"

#Array of VT data
VT = np.array([VTstate,
               VT7case,
               VT7case100,
               VTcase,
               VTcase100,
               VTvacc1per,
               VTvacc1,
               VTvacc2per,
               VTvacc2])

In [736]:
#Virginia Cases

#State
VAstate = "VA"

#Cases in the last 7 days
VA7case = "09788"

#Cases in the last 7 days per 100k people
VA7case100 = "114.7"

#Total Cases
VAcase = "0964887"

#Total Cases per 100k people
VAcase100 = "11304"

#Virginia Vaccinations

#% with 1 dose
VAvacc1per = "74.90"

#1 dose
VAvacc1 = "06393468"

#% with 2 doses
VAvacc2per = "64.62"

#2 doses
VAvacc2 = "05516063"

#Array of VA data
VA = np.array([VAstate,
               VA7case,
               VA7case100,
               VAcase,
               VAcase100,
               VAvacc1per,
               VAvacc1,
               VAvacc2per,
               VAvacc2])

In [737]:
#Washington Cases

#State
WAstate = "WA"

#Cases in the last 7 days
WA7case = "06033"

#Cases in the last 7 days per 100k people
WA7case100 = "079.2"

#Total Cases
WAcase = "0768151"

#Total Cases per 100k people
WAcase100 = "10088"

#Washington Vaccinations

#% with 1 dose
WAvacc1per = "72.34"

#1 dose
WAvacc1 = "05508609"

#% with 2 doses
WAvacc2per = "64.81"

#2 doses
WAvacc2 = "04935124"

#Array of WA data
WA = np.array([WAstate,
               WA7case,
               WA7case100,
               WAcase,
               WAcase100,
               WAvacc1per,
               WAvacc1,
               WAvacc2per,
               WAvacc2])

In [738]:
#West Virginia Cases

#State
WVstate = "WV"

#Cases in the last 7 days
WV7case = "03297"

#Cases in the last 7 days per 100k people
WV7case100 = "184.0"

#Total Cases
WVcase = "0290909"

#Total Cases per 100k people
WVcase100 = "16232"

#Vest Virginia Vaccinations

#% with 1 dose
WVvacc1per = "53.84"

#1 dose
WVvacc1 = "00964820"

#% with 2 doses
WVvacc2per = "41.51"

#2 doses
WVvacc2 = "00744003"

#Array of WV data
WV = np.array([WVstate,
               WV7case,
               WV7case100,
               WVcase,
               WVcase100,
               WVvacc1per,
               WVvacc1,
               WVvacc2per,
               WVvacc2])

In [739]:
#Wisconsin Cases

#State
WIstate = "WI"

#Cases in the last 7 days
WI7case = "22576"

#Cases in the last 7 days per 100k people
WI7case100 = "387.7"

#Total Cases
WIcase = "0968291"

#Total Cases per 100k people
WIcase100 = "16630"

#Wisconsin Vaccinations

#% with 1 dose
WIvacc1per = "65.40"

#1 dose
WIvacc1 = "03807811"

#% with 2 doses
WIvacc2per = "59.30"

#2 doses
WIvacc2 = "03452828"

#Array of WI data
WI = np.array([WIstate,
               WI7case,
               WI7case100,
               WIcase,
               WIcase100,
               WIvacc1per,
               WIvacc1,
               WIvacc2per,
               WIvacc2])

In [740]:
#Wyoming Cases

#State
WYstate = "WY"

#Cases in the last 7 days
WY7case = "00946"

#Cases in the last 7 days per 100k people
WY7case100 = "163.5"

#Total Cases
WYcase = "0110264"

#Total Cases per 100k people
WYcase100 = "19052"

#Wyoming Vaccinations

#% with 1 dose
WYvacc1per = "53.20"

#1 dose
WYvacc1 = "00307923"

#% with 2 doses
WYvacc2per = "45.34"

#2 doses
WYvacc2 = "00262417"

#Array of WY data
WY = np.array([WYstate,
               WY7case,
               WY7case100,
               WYcase,
               WYcase100,
               WYvacc1per,
               WYvacc1,
               WYvacc2per,
               WYvacc2])

In [741]:
#Table header
header = np.hstack((np.array(["State"]),
                    np.array(["Cases in Last 7 Days"]),
                    np.array(["Cases in Last 7 Days / 100k People"]),
                    np.array(["Total Cases"]),
                    np.array(["Total Cases / 100k People"]),
                    np.array(["% of People with 1 Dose"]),
                    np.array(["People with 1 Dose"]),
                    np.array(["% of People with 2 Doses"]),
                    np.array(["People with 2 Doses"])))

In [742]:
#Sorted by state
stateSort = np.vstack((AL, AK, AZ, AR, CA,
                       CO, CT, DE, DC, FL,
                       GA, HI, ID, IL, IN,
                       IA, KS, KY, LA, ME,
                       MD, MA, MI, MN, MS,
                       MO, MT, NE, NV, NH,
                       NJ, NM, NY, NC, ND,
                       OH, OK, OR, PA, RI,
                       SC, SD, TN, TX, UT,
                       VT, VA, WA, WV, WI,
                       WY))

In [743]:
sortSelect = input("0. State\n\
1. Cases in Last 7 Days\n\
2. Cases in Last 7 Days / 100k People\n\
3. Total Cases\n\
4. Total Cases / 100k People\n\
5. % of People with 1 Dose\n\
6. People with 1 Dose\n\
7. % of People with 2 Doses\n\
8. People with 2 Doses\n\n\
Please select how you want to sort the data, using an integer from 0 to 8 inclusive: ")

while sortSelect != "0" and \
sortSelect != "1" and \
sortSelect != "2" and \
sortSelect != "3" and \
sortSelect != "4" and \
sortSelect != "5" and \
sortSelect != "6" and \
sortSelect != "7" and \
sortSelect != "8":
    sortSelect = input("Input a number between 0 and 8 inclusive as your selection: ")

0. State
1. Cases in Last 7 Days
2. Cases in Last 7 Days / 100k People
3. Total Cases
4. Total Cases / 100k People
5. % of People with 1 Dose
6. People with 1 Dose
7. % of People with 2 Doses
8. People with 2 Doses

Please select how you want to sort the data, using an integer from 0 to 8 inclusive: 2

In [744]:
upDownSel = input("Input '0' to sort the data in ascending order. \
Input '1' to sort the data in descending order: ")

while upDownSel != "0" and upDownSel != "1":
    upDownSel = input("Input '0' or '1' to sort the data in ascending or descending order respectively: ")

Input '0' to sort the data in ascending order. Input '1' to sort the data in descending order: 0

In [745]:
sortSelect = int(sortSelect)
upDownSel = int(upDownSel)

In [746]:
sortedTable = stateSort[stateSort[:,sortSelect].argsort()]

sortedTable[:,1] = sortedTable[:,1].astype(int)
sortedTable[:,2] = sortedTable[:,2].astype(float)
sortedTable[:,3] = sortedTable[:,3].astype(int)
sortedTable[:,4] = sortedTable[:,4].astype(int)
sortedTable[:,5] = sortedTable[:,5].astype(float)
sortedTable[:,6] = sortedTable[:,6].astype(int)
sortedTable[:,7] = sortedTable[:,7].astype(float)
sortedTable[:,8] = sortedTable[:,8].astype(int)

In [752]:
if sortSelect == int(0):
    if upDownSel == int(0):
        display(HTML(tabulate.tabulate(np.vstack((header, stateSort)), tablefmt='html')))
    else:
        display(HTML(tabulate.tabulate(np.vstack((header, np.flipud(stateSort))), tablefmt='html')))
else:
    if upDownSel == int(0):
        display(HTML(tabulate.tabulate(np.vstack((header, stateSort[stateSort[:,sortSelect].argsort()])), tablefmt='html')))
        print("The state with the least " + header[sortSelect] + " is " + sortedTable[0,0] + " with " + \
              sortedTable[0,sortSelect] + ".")
        print("The state with the most " + header[sortSelect] + " is " + np.flipud(sortedTable)[0,0] + \
              " with " + np.flipud(sortedTable)[0,sortSelect] + ".")
        print("The state with the median of " + header[sortSelect] + " is " + sortedTable[25,0] + " with " + \
              round(np.median(sortedTable[:,sortSelect].astype(float)),2).astype(str) + ".")
        print("The average of " + header[sortSelect] + " is " + \
              round(np.mean(sortedTable[:,sortSelect].astype(float)),2).astype(str) + ".")
    else:
        display(HTML(tabulate.tabulate(np.vstack((header, np.flipud(stateSort[stateSort[:,sortSelect].argsort()]))), tablefmt='html')))
        print("The state with the most " + header[sortSelect] + " is " + np.flipud(sortedTable)[0,0] + \
              " with " + np.flipud(sortedTable)[0,sortSelect] + ".")
        print("The state with the least " + header[sortSelect] + " is " + sortedTable[0,0] + " with " + \
              sortedTable[0,sortSelect] + ".")
        print("The state with the median of " + header[sortSelect] + " is " + sortedTable[25,0] + " with " + \
              round(np.median(sortedTable[:,sortSelect].astype(float)),2).astype(str) + ".")
        print("The average of " + header[sortSelect] + " is " + \
              round(np.mean(sortedTable[:,sortSelect].astype(float)),2).astype(str) + ".")

print("\nCOVID case data as recent as " + caseDate + ".")
print("COVID vaccine data as recent as " + vaccDate + ".")

The state with the least Cases in Last 7 Days / 100k People is FL with 27.4.
The state with the most Cases in Last 7 Days / 100k People is MN with 426.0.
The average of Cases in Last 7 Days / 100k People is 186.3.
The state with the median of Cases in Last 7 Days / 100k People is WV with 184.0.

COVID case data as recent as 11-28-2021.
COVID vaccine data as recent as 11-24-2021.